// Theme constants and color structure definitions
export interface ThemeColors {
  // Primary colors
  background: string;
  foreground: string;
  card: string;
  cardForeground: string;
  popover: string;
  popoverForeground: string;
  
  // Brand colors
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  accent: string;
  accentForeground: string;
  
  // UI colors
  muted: string;
  mutedForeground: string;
  destructive: string;
  destructiveForeground: string;
  border: string;
  input: string;
  inputBackground: string;
  switchBackground: string;
  ring: string;
  
  // Chart colors
  chart1: string;
  chart2: string;
  chart3: string;
  chart4: string;
  chart5: string;
  
  // Sidebar colors
  sidebar: string;
  sidebarForeground: string;
  sidebarPrimary: string;
  sidebarPrimaryForeground: string;
  sidebarAccent: string;
  sidebarAccentForeground: string;
  sidebarBorder: string;
  sidebarRing: string;
}

export interface ThemeConfig {
  id: string;
  name: string;
  description: string;
  light: ThemeColors;
  dark: ThemeColors;
  isDefault?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

// Default theme configurations
export const DEFAULT_LIGHT_THEME: ThemeColors = {
  background: '#F8FAFC',
  foreground: '#334155',
  card: '#EDE9FE',
  cardForeground: '#334155',
  popover: '#EDE9FE',
  popoverForeground: '#334155',
  primary: '#7C3AED',
  primaryForeground: '#ffffff',
  secondary: '#0EA5E9',
  secondaryForeground: '#ffffff',
  accent: '#FB7185',
  accentForeground: '#ffffff',
  muted: '#F1F5F9',
  mutedForeground: '#64748B',
  destructive: '#EF4444',
  destructiveForeground: '#ffffff',
  border: '#CBD5E1',
  input: 'transparent',
  inputBackground: '#ffffff',
  switchBackground: '#CBD5E1',
  ring: '#7C3AED',
  chart1: '#7C3AED',
  chart2: '#0EA5E9',
  chart3: '#FB7185',
  chart4: '#10B981',
  chart5: '#F59E0B',
  sidebar: '#F8FAFC',
  sidebarForeground: '#334155',
  sidebarPrimary: '#7C3AED',
  sidebarPrimaryForeground: '#ffffff',
  sidebarAccent: '#F1F5F9',
  sidebarAccentForeground: '#334155',
  sidebarBorder: '#CBD5E1',
  sidebarRing: '#7C3AED',
};

export const DEFAULT_DARK_THEME: ThemeColors = {
  background: '#0F172A',
  foreground: '#F1F5F9',
  card: '#1E293B',
  cardForeground: '#F1F5F9',
  popover: '#1E293B',
  popoverForeground: '#F1F5F9',
  primary: '#8B5CF6',
  primaryForeground: '#ffffff',
  secondary: '#0EA5E9',
  secondaryForeground: '#ffffff',
  accent: '#FB7185',
  accentForeground: '#ffffff',
  muted: '#334155',
  mutedForeground: '#94A3B8',
  destructive: '#EF4444',
  destructiveForeground: '#ffffff',
  border: '#475569',
  input: '#334155',
  inputBackground: '#334155',
  switchBackground: '#475569',
  ring: '#8B5CF6',
  chart1: '#8B5CF6',
  chart2: '#0EA5E9',
  chart3: '#FB7185',
  chart4: '#10B981',
  chart5: '#F59E0B',
  sidebar: '#1E293B',
  sidebarForeground: '#F1F5F9',
  sidebarPrimary: '#8B5CF6',
  sidebarPrimaryForeground: '#ffffff',
  sidebarAccent: '#334155',
  sidebarAccentForeground: '#F1F5F9',
  sidebarBorder: '#475569',
  sidebarRing: '#8B5CF6',
};

// Pre-built theme configurations
export const PREDEFINED_THEMES: ThemeConfig[] = [
  {
    id: 'default',
    name: 'Default Purple',
    description: 'The classic purple and blue theme',
    light: DEFAULT_LIGHT_THEME,
    dark: DEFAULT_DARK_THEME,
    isDefault: true,
  },
  {
    id: 'emerald',
    name: 'Emerald Green',
    description: 'Fresh green color scheme',
    light: {
      ...DEFAULT_LIGHT_THEME,
      primary: '#10B981',
      ring: '#10B981',
      chart1: '#10B981',
      sidebarPrimary: '#10B981',
      sidebarRing: '#10B981',
    },
    dark: {
      ...DEFAULT_DARK_THEME,
      primary: '#34D399',
      ring: '#34D399',
      chart1: '#34D399',
      sidebarPrimary: '#34D399',
      sidebarRing: '#34D399',
    },
  },
  {
    id: 'blue',
    name: 'Ocean Blue',
    description: 'Calming blue tones',
    light: {
      ...DEFAULT_LIGHT_THEME,
      primary: '#0EA5E9',
      ring: '#0EA5E9',
      chart1: '#0EA5E9',
      sidebarPrimary: '#0EA5E9',
      sidebarRing: '#0EA5E9',
    },
    dark: {
      ...DEFAULT_DARK_THEME,
      primary: '#38BDF8',
      ring: '#38BDF8',
      chart1: '#38BDF8',
      sidebarPrimary: '#38BDF8',
      sidebarRing: '#38BDF8',
    },
  },
  {
    id: 'orange',
    name: 'Sunset Orange',
    description: 'Warm orange and amber theme',
    light: {
      ...DEFAULT_LIGHT_THEME,
      primary: '#F97316',
      ring: '#F97316',
      chart1: '#F97316',
      sidebarPrimary: '#F97316',
      sidebarRing: '#F97316',
    },
    dark: {
      ...DEFAULT_DARK_THEME,
      primary: '#FB923C',
      ring: '#FB923C',
      chart1: '#FB923C',
      sidebarPrimary: '#FB923C',
      sidebarRing: '#FB923C',
    },
  },
  {
    id: 'rose',
    name: 'Rose Pink',
    description: 'Elegant rose and pink tones',
    light: {
      ...DEFAULT_LIGHT_THEME,
      primary: '#E11D48',
      ring: '#E11D48',
      chart1: '#E11D48',
      sidebarPrimary: '#E11D48',
      sidebarRing: '#E11D48',
    },
    dark: {
      ...DEFAULT_DARK_THEME,
      primary: '#F43F5E',
      ring: '#F43F5E',
      chart1: '#F43F5E',
      sidebarPrimary: '#F43F5E',
      sidebarRing: '#F43F5E',
    },
  },
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    description: 'Clean and modern with accessible contrast',
    light: {
      background: '#FFFFFF',
      foreground: '#1F2937',
      card: '#FFFFFF',
      cardForeground: '#1F2937',
      popover: '#FFFFFF',
      popoverForeground: '#1F2937',
      primary: '#4A90E2',
      primaryForeground: '#FFFFFF',
      secondary: '#6B7280',
      secondaryForeground: '#FFFFFF',
      accent: '#00C897',
      accentForeground: '#FFFFFF',
      muted: '#F4F6F8',
      mutedForeground: '#6B7280',
      destructive: '#FF4C4C',
      destructiveForeground: '#FFFFFF',
      border: '#E5E7EB',
      input: 'transparent',
      inputBackground: '#FFFFFF',
      switchBackground: '#E5E7EB',
      ring: '#4A90E2',
      chart1: '#4A90E2',
      chart2: '#00C897',
      chart3: '#6B7280',
      chart4: '#10B981',
      chart5: '#F59E0B',
      sidebar: '#FFFFFF',
      sidebarForeground: '#1F2937',
      sidebarPrimary: '#4A90E2',
      sidebarPrimaryForeground: '#FFFFFF',
      sidebarAccent: '#F4F6F8',
      sidebarAccentForeground: '#1F2937',
      sidebarBorder: '#E5E7EB',
      sidebarRing: '#4A90E2',
    },
    dark: {
      background: '#121212',
      foreground: '#E5E5E5',
      card: '#1E1E1E',
      cardForeground: '#E5E5E5',
      popover: '#1E1E1E',
      popoverForeground: '#E5E5E5',
      primary: '#4A90E2',
      primaryForeground: '#FFFFFF',
      secondary: '#9CA3AF',
      secondaryForeground: '#FFFFFF',
      accent: '#00C897',
      accentForeground: '#FFFFFF',
      muted: '#2C2C2C',
      mutedForeground: '#9CA3AF',
      destructive: '#FF4C4C',
      destructiveForeground: '#FFFFFF',
      border: '#2C2C2C',
      input: '#2C2C2C',
      inputBackground: '#2C2C2C',
      switchBackground: '#2C2C2C',
      ring: '#4A90E2',
      chart1: '#4A90E2',
      chart2: '#00C897',
      chart3: '#9CA3AF',
      chart4: '#10B981',
      chart5: '#FBBF24',
      sidebar: '#1E1E1E',
      sidebarForeground: '#E5E5E5',
      sidebarPrimary: '#4A90E2',
      sidebarPrimaryForeground: '#FFFFFF',
      sidebarAccent: '#2C2C2C',
      sidebarAccentForeground: '#E5E5E5',
      sidebarBorder: '#2C2C2C',
      sidebarRing: '#4A90E2',
    },
  },
  {
    id: 'professional',
    name: 'Professional Corporate',
    description: 'Blue and gray for corporate environments',
    light: {
      background: '#FFFFFF',
      foreground: '#1F2937',
      card: '#FFFFFF',
      cardForeground: '#1F2937',
      popover: '#FFFFFF',
      popoverForeground: '#1F2937',
      primary: '#4A90E2',
      primaryForeground: '#FFFFFF',
      secondary: '#6B7280',
      secondaryForeground: '#FFFFFF',
      accent: '#0EA5E9',
      accentForeground: '#FFFFFF',
      muted: '#F9FAFB',
      mutedForeground: '#6B7280',
      destructive: '#EF4444',
      destructiveForeground: '#FFFFFF',
      border: '#E5E7EB',
      input: 'transparent',
      inputBackground: '#FFFFFF',
      switchBackground: '#E5E7EB',
      ring: '#4A90E2',
      chart1: '#4A90E2',
      chart2: '#6B7280',
      chart3: '#0EA5E9',
      chart4: '#10B981',
      chart5: '#F59E0B',
      sidebar: '#F9FAFB',
      sidebarForeground: '#1F2937',
      sidebarPrimary: '#4A90E2',
      sidebarPrimaryForeground: '#FFFFFF',
      sidebarAccent: '#F3F4F6',
      sidebarAccentForeground: '#1F2937',
      sidebarBorder: '#E5E7EB',
      sidebarRing: '#4A90E2',
    },
    dark: {
      background: '#111827',
      foreground: '#F9FAFB',
      card: '#1F2937',
      cardForeground: '#F9FAFB',
      popover: '#1F2937',
      popoverForeground: '#F9FAFB',
      primary: '#60A5FA',
      primaryForeground: '#FFFFFF',
      secondary: '#9CA3AF',
      secondaryForeground: '#FFFFFF',
      accent: '#22D3EE',
      accentForeground: '#FFFFFF',
      muted: '#374151',
      mutedForeground: '#D1D5DB',
      destructive: '#F87171',
      destructiveForeground: '#FFFFFF',
      border: '#374151',
      input: '#374151',
      inputBackground: '#374151',
      switchBackground: '#4B5563',
      ring: '#60A5FA',
      chart1: '#60A5FA',
      chart2: '#9CA3AF',
      chart3: '#22D3EE',
      chart4: '#34D399',
      chart5: '#FBBF24',
      sidebar: '#1F2937',
      sidebarForeground: '#F9FAFB',
      sidebarPrimary: '#60A5FA',
      sidebarPrimaryForeground: '#FFFFFF',
      sidebarAccent: '#374151',
      sidebarAccentForeground: '#F9FAFB',
      sidebarBorder: '#374151',
      sidebarRing: '#60A5FA',
    },
  },
  {
    id: 'friendly-edtech',
    name: 'Friendly EdTech',
    description: 'Blue and green for school environments',
    light: {
      background: '#FDF6EC',
      foreground: '#1F2937',
      card: '#FFFFFF',
      cardForeground: '#1F2937',
      popover: '#FFFFFF',
      popoverForeground: '#1F2937',
      primary: '#4A90E2',
      primaryForeground: '#FFFFFF',
      secondary: '#10B981',
      secondaryForeground: '#FFFFFF',
      accent: '#00C897',
      accentForeground: '#FFFFFF',
      muted: '#FEF3E2',
      mutedForeground: '#78716C',
      destructive: '#EF4444',
      destructiveForeground: '#FFFFFF',
      border: '#F5E6D3',
      input: 'transparent',
      inputBackground: '#FFFFFF',
      switchBackground: '#F5E6D3',
      ring: '#4A90E2',
      chart1: '#4A90E2',
      chart2: '#10B981',
      chart3: '#00C897',
      chart4: '#84CC16',
      chart5: '#FBBF24',
      sidebar: '#FDF6EC',
      sidebarForeground: '#1F2937',
      sidebarPrimary: '#4A90E2',
      sidebarPrimaryForeground: '#FFFFFF',
      sidebarAccent: '#FEF3E2',
      sidebarAccentForeground: '#1F2937',
      sidebarBorder: '#F5E6D3',
      sidebarRing: '#4A90E2',
    },
    dark: {
      background: '#1C1917',
      foreground: '#FEF3E2',
      card: '#292524',
      cardForeground: '#FEF3E2',
      popover: '#292524',
      popoverForeground: '#FEF3E2',
      primary: '#60A5FA',
      primaryForeground: '#FFFFFF',
      secondary: '#34D399',
      secondaryForeground: '#FFFFFF',
      accent: '#10D9A0',
      accentForeground: '#FFFFFF',
      muted: '#44403C',
      mutedForeground: '#D6D3D1',
      destructive: '#F87171',
      destructiveForeground: '#FFFFFF',
      border: '#57534E',
      input: '#44403C',
      inputBackground: '#44403C',
      switchBackground: '#57534E',
      ring: '#60A5FA',
      chart1: '#60A5FA',
      chart2: '#34D399',
      chart3: '#10D9A0',
      chart4: '#A3E635',
      chart5: '#FCD34D',
      sidebar: '#292524',
      sidebarForeground: '#FEF3E2',
      sidebarPrimary: '#60A5FA',
      sidebarPrimaryForeground: '#FFFFFF',
      sidebarAccent: '#44403C',
      sidebarAccentForeground: '#FEF3E2',
      sidebarBorder: '#57534E',
      sidebarRing: '#60A5FA',
    },
  },
  {
    id: 'energetic-startup',
    name: 'Energetic Startup',
    description: 'Purple and aqua for mobile-first design',
    light: {
      background: '#FFFFFF',
      foreground: '#1F2937',
      card: '#FFFFFF',
      cardForeground: '#1F2937',
      popover: '#FFFFFF',
      popoverForeground: '#1F2937',
      primary: '#7F56D9',
      primaryForeground: '#FFFFFF',
      secondary: '#3CD4A0',
      secondaryForeground: '#FFFFFF',
      accent: '#06B6D4',
      accentForeground: '#FFFFFF',
      muted: '#F9FAFB',
      mutedForeground: '#6B7280',
      destructive: '#EF4444',
      destructiveForeground: '#FFFFFF',
      border: '#E5E7EB',
      input: 'transparent',
      inputBackground: '#FFFFFF',
      switchBackground: '#E5E7EB',
      ring: '#7F56D9',
      chart1: '#7F56D9',
      chart2: '#3CD4A0',
      chart3: '#06B6D4',
      chart4: '#F59E0B',
      chart5: '#EC4899',
      sidebar: '#F9FAFB',
      sidebarForeground: '#1F2937',
      sidebarPrimary: '#7F56D9',
      sidebarPrimaryForeground: '#FFFFFF',
      sidebarAccent: '#F3F4F6',
      sidebarAccentForeground: '#1F2937',
      sidebarBorder: '#E5E7EB',
      sidebarRing: '#7F56D9',
    },
    dark: {
      background: '#0F0F1E',
      foreground: '#F3F4F6',
      card: '#1A1A2E',
      cardForeground: '#F3F4F6',
      popover: '#1A1A2E',
      popoverForeground: '#F3F4F6',
      primary: '#9B7FED',
      primaryForeground: '#FFFFFF',
      secondary: '#4ADEAA',
      secondaryForeground: '#FFFFFF',
      accent: '#22D3EE',
      accentForeground: '#FFFFFF',
      muted: '#2E2E48',
      mutedForeground: '#D1D5DB',
      destructive: '#F87171',
      destructiveForeground: '#FFFFFF',
      border: '#3F3F5E',
      input: '#2E2E48',
      inputBackground: '#2E2E48',
      switchBackground: '#3F3F5E',
      ring: '#9B7FED',
      chart1: '#9B7FED',
      chart2: '#4ADEAA',
      chart3: '#22D3EE',
      chart4: '#FBBF24',
      chart5: '#F472B6',
      sidebar: '#1A1A2E',
      sidebarForeground: '#F3F4F6',
      sidebarPrimary: '#9B7FED',
      sidebarPrimaryForeground: '#FFFFFF',
      sidebarAccent: '#2E2E48',
      sidebarAccentForeground: '#F3F4F6',
      sidebarBorder: '#3F3F5E',
      sidebarRing: '#9B7FED',
    },
  },
  {
    id: 'soft-lavender',
    name: 'Soft Lavender',
    description: 'Gentle lavender and pastel tones',
    light: {
      background: '#FAF9FC',
      foreground: '#2D2438',
      card: '#FFFFFF',
      cardForeground: '#2D2438',
      popover: '#FFFFFF',
      popoverForeground: '#2D2438',
      primary: '#9B87F5',
      primaryForeground: '#FFFFFF',
      secondary: '#D4BBF7',
      secondaryForeground: '#2D2438',
      accent: '#E5DEFF',
      accentForeground: '#2D2438',
      muted: '#F5F3F7',
      mutedForeground: '#6B5B8C',
      destructive: '#EF4444',
      destructiveForeground: '#FFFFFF',
      border: '#E9E3F0',
      input: 'transparent',
      inputBackground: '#FFFFFF',
      switchBackground: '#E9E3F0',
      ring: '#9B87F5',
      chart1: '#9B87F5',
      chart2: '#D4BBF7',
      chart3: '#8B5CF6',
      chart4: '#A78BFA',
      chart5: '#C4B5FD',
      sidebar: '#FAF9FC',
      sidebarForeground: '#2D2438',
      sidebarPrimary: '#9B87F5',
      sidebarPrimaryForeground: '#FFFFFF',
      sidebarAccent: '#F5F3F7',
      sidebarAccentForeground: '#2D2438',
      sidebarBorder: '#E9E3F0',
      sidebarRing: '#9B87F5',
    },
    dark: {
      background: '#1A1625',
      foreground: '#F5F3F7',
      card: '#251F35',
      cardForeground: '#F5F3F7',
      popover: '#251F35',
      popoverForeground: '#F5F3F7',
      primary: '#A78BFA',
      primaryForeground: '#FFFFFF',
      secondary: '#8B5CF6',
      secondaryForeground: '#FFFFFF',
      accent: '#C4B5FD',
      accentForeground: '#1A1625',
      muted: '#3A2F52',
      mutedForeground: '#D1C9E0',
      destructive: '#F87171',
      destructiveForeground: '#FFFFFF',
      border: '#4A3F68',
      input: '#3A2F52',
      inputBackground: '#3A2F52',
      switchBackground: '#4A3F68',
      ring: '#A78BFA',
      chart1: '#A78BFA',
      chart2: '#C4B5FD',
      chart3: '#8B5CF6',
      chart4: '#9B87F5',
      chart5: '#DDD6FE',
      sidebar: '#251F35',
      sidebarForeground: '#F5F3F7',
      sidebarPrimary: '#A78BFA',
      sidebarPrimaryForeground: '#FFFFFF',
      sidebarAccent: '#3A2F52',
      sidebarAccentForeground: '#F5F3F7',
      sidebarBorder: '#4A3F68',
      sidebarRing: '#A78BFA',
    },
  },
  {
    id: 'forest-green',
    name: 'Forest Green',
    description: 'Deep green tones inspired by nature',
    light: {
      background: '#F7FDF9',
      foreground: '#14532D',
      card: '#FFFFFF',
      cardForeground: '#14532D',
      popover: '#FFFFFF',
      popoverForeground: '#14532D',
      primary: '#059669',
      primaryForeground: '#FFFFFF',
      secondary: '#10B981',
      secondaryForeground: '#FFFFFF',
      accent: '#34D399',
      accentForeground: '#14532D',
      muted: '#F0FDF4',
      mutedForeground: '#166534',
      destructive: '#DC2626',
      destructiveForeground: '#FFFFFF',
      border: '#D1FAE5',
      input: 'transparent',
      inputBackground: '#FFFFFF',
      switchBackground: '#D1FAE5',
      ring: '#059669',
      chart1: '#059669',
      chart2: '#10B981',
      chart3: '#34D399',
      chart4: '#6EE7B7',
      chart5: '#A7F3D0',
      sidebar: '#F7FDF9',
      sidebarForeground: '#14532D',
      sidebarPrimary: '#059669',
      sidebarPrimaryForeground: '#FFFFFF',
      sidebarAccent: '#F0FDF4',
      sidebarAccentForeground: '#14532D',
      sidebarBorder: '#D1FAE5',
      sidebarRing: '#059669',
    },
    dark: {
      background: '#022C22',
      foreground: '#F0FDF4',
      card: '#064E3B',
      cardForeground: '#F0FDF4',
      popover: '#064E3B',
      popoverForeground: '#F0FDF4',
      primary: '#34D399',
      primaryForeground: '#022C22',
      secondary: '#10B981',
      secondaryForeground: '#FFFFFF',
      accent: '#6EE7B7',
      accentForeground: '#022C22',
      muted: '#065F46',
      mutedForeground: '#D1FAE5',
      destructive: '#F87171',
      destructiveForeground: '#FFFFFF',
      border: '#047857',
      input: '#065F46',
      inputBackground: '#065F46',
      switchBackground: '#047857',
      ring: '#34D399',
      chart1: '#34D399',
      chart2: '#10B981',
      chart3: '#6EE7B7',
      chart4: '#A7F3D0',
      chart5: '#D1FAE5',
      sidebar: '#064E3B',
      sidebarForeground: '#F0FDF4',
      sidebarPrimary: '#34D399',
      sidebarPrimaryForeground: '#022C22',
      sidebarAccent: '#065F46',
      sidebarAccentForeground: '#F0FDF4',
      sidebarBorder: '#047857',
      sidebarRing: '#34D399',
    },
  },
  {
    id: 'warm-amber',
    name: 'Warm Amber',
    description: 'Cozy amber and orange tones',
    light: {
      background: '#FFFBF5',
      foreground: '#451A03',
      card: '#FFFFFF',
      cardForeground: '#451A03',
      popover: '#FFFFFF',
      popoverForeground: '#451A03',
      primary: '#D97706',
      primaryForeground: '#FFFFFF',
      secondary: '#F59E0B',
      secondaryForeground: '#FFFFFF',
      accent: '#FBBF24',
      accentForeground: '#451A03',
      muted: '#FEF3C7',
      mutedForeground: '#92400E',
      destructive: '#DC2626',
      destructiveForeground: '#FFFFFF',
      border: '#FDE68A',
      input: 'transparent',
      inputBackground: '#FFFFFF',
      switchBackground: '#FDE68A',
      ring: '#D97706',
      chart1: '#D97706',
      chart2: '#F59E0B',
      chart3: '#FBBF24',
      chart4: '#FCD34D',
      chart5: '#FDE68A',
      sidebar: '#FFFBF5',
      sidebarForeground: '#451A03',
      sidebarPrimary: '#D97706',
      sidebarPrimaryForeground: '#FFFFFF',
      sidebarAccent: '#FEF3C7',
      sidebarAccentForeground: '#451A03',
      sidebarBorder: '#FDE68A',
      sidebarRing: '#D97706',
    },
    dark: {
      background: '#1C1410',
      foreground: '#FEF3C7',
      card: '#292218',
      cardForeground: '#FEF3C7',
      popover: '#292218',
      popoverForeground: '#FEF3C7',
      primary: '#FBBF24',
      primaryForeground: '#1C1410',
      secondary: '#F59E0B',
      secondaryForeground: '#1C1410',
      accent: '#FCD34D',
      accentForeground: '#1C1410',
      muted: '#3F3526',
      mutedForeground: '#FDE68A',
      destructive: '#F87171',
      destructiveForeground: '#FFFFFF',
      border: '#57493A',
      input: '#3F3526',
      inputBackground: '#3F3526',
      switchBackground: '#57493A',
      ring: '#FBBF24',
      chart1: '#FBBF24',
      chart2: '#F59E0B',
      chart3: '#FCD34D',
      chart4: '#FDE68A',
      chart5: '#FEF3C7',
      sidebar: '#292218',
      sidebarForeground: '#FEF3C7',
      sidebarPrimary: '#FBBF24',
      sidebarPrimaryForeground: '#1C1410',
      sidebarAccent: '#3F3526',
      sidebarAccentForeground: '#FEF3C7',
      sidebarBorder: '#57493A',
      sidebarRing: '#FBBF24',
    },
  },
];

// CSS variable mapping
export const CSS_VARIABLE_MAP: Record<keyof ThemeColors, string> = {
  background: '--background',
  foreground: '--foreground',
  card: '--card',
  cardForeground: '--card-foreground',
  popover: '--popover',
  popoverForeground: '--popover-foreground',
  primary: '--primary',
  primaryForeground: '--primary-foreground',
  secondary: '--secondary',
  secondaryForeground: '--secondary-foreground',
  accent: '--accent',
  accentForeground: '--accent-foreground',
  muted: '--muted',
  mutedForeground: '--muted-foreground',
  destructive: '--destructive',
  destructiveForeground: '--destructive-foreground',
  border: '--border',
  input: '--input',
  inputBackground: '--input-background',
  switchBackground: '--switch-background',
  ring: '--ring',
  chart1: '--chart-1',
  chart2: '--chart-2',
  chart3: '--chart-3',
  chart4: '--chart-4',
  chart5: '--chart-5',
  sidebar: '--sidebar',
  sidebarForeground: '--sidebar-foreground',
  sidebarPrimary: '--sidebar-primary',
  sidebarPrimaryForeground: '--sidebar-primary-foreground',
  sidebarAccent: '--sidebar-accent',
  sidebarAccentForeground: '--sidebar-accent-foreground',
  sidebarBorder: '--sidebar-border',
  sidebarRing: '--sidebar-ring',
};

// Theme validation
export const validateThemeColors = (colors: Partial<ThemeColors>): boolean => {
  const requiredFields: (keyof ThemeColors)[] = [
    'background',
    'foreground',
    'primary',
    'primaryForeground',
  ];
  
  return requiredFields.every(field => {
    const value = colors[field];
    return typeof value === 'string' && value.length > 0;
  });
};

// Color utility functions
export const isValidHexColor = (color: string): boolean => {
  return /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/.test(color);
};

export const isValidRgbColor = (color: string): boolean => {
  return /^rgb\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*\)$/.test(color);
};

export const isValidColor = (color: string): boolean => {
  return isValidHexColor(color) || isValidRgbColor(color);
};